fragment SlimCopyrightData on Copyright {
  id
  name
  sort_name
  aliases
  favorite
  image_path
}

fragment CopyrightListData on Copyright {
  ...SlimCopyrightData
  description
  image_count
  scene_count
  performer_count
  subtree_image_count
  subtree_scene_count
  subtree_performer_count
  structural_role
}

fragment CopyrightData on Copyright {
  id
  name
  sort_name
  description
  aliases
  favorite
  image_path
  created_at
  updated_at
  image_count
  scene_count
  performer_count
  subtree_image_count
  subtree_scene_count
  subtree_performer_count
  structural_role
  parents {
    ...SlimCopyrightData
  }
  children {
    ...SlimCopyrightData
  }
  ordered_children {
    ...SlimCopyrightData
  }
  breadcrumb {
    ...SlimCopyrightData
  }
  scenes {
    id
    title
    paths {
      screenshot
    }
  }
  performers {
    id
    name
    disambiguation
    alias_list
    image_path
    birthdate
    death_date
  }
  subtree_performers {
    id
  }
}
