fragment SlimCopyrightData on Copyright {
  id
  name
  sort_name
  aliases
  favorite
  image_path
}

fragment CopyrightData on Copyright {
  id
  name
  sort_name
  description
  aliases
  favorite
  image_path
  created_at
  updated_at
  image_count
  scene_count
  performer_count
  parents {
    ...SlimCopyrightData
  }
  children {
    ...SlimCopyrightData
  }
  images {
    id
    title
    paths {
      thumbnail
      image
    }
  }
  scenes {
    id
    title
    paths {
      screenshot
    }
  }
  performers {
    id
    name
    disambiguation
    image_path
  }
}
