fragment ImageData on Image {
  id
  title
  code
  rating100
  date
  urls
  details
  photographer
  organized
  o_counter
  created_at
  updated_at

  paths {
    thumbnail
    preview
    image
  }

  galleries {
    ...GalleryData
  }

  studio {
    ...SlimStudioData
  }

  artists {
    ...SlimStudioData
  }

  tags {
    ...SlimTagData
  }

  copyrights {
    ...SlimCopyrightData
    breadcrumb {
      ...SlimCopyrightData
    }
  }

  ordered_copyrights {
    ...SlimCopyrightData
    breadcrumb {
      ...SlimCopyrightData
    }
  }

  primary_copyright {
    ...SlimCopyrightData
  }

  performers {
    ...PerformerData
  }

  visual_files {
    ...VisualFileData
  }

  custom_fields
}