mutation CopyrightCreate($input: CopyrightCreateInput!) {
  copyrightCreate(input: $input) {
    ...CopyrightData
  }
}

mutation CopyrightUpdate($input: CopyrightUpdateInput!) {
  copyrightUpdate(input: $input) {
    ...CopyrightData
  }
}

mutation CopyrightDestroy($id: ID!) {
  copyrightDestroy(input: { id: $id })
}

mutation ImageCopyrightsUpdate($imageID: ID!, $copyrightIDs: [ID!]!) {
  imageCopyrightsUpdate(image_id: $imageID, copyright_ids: $copyrightIDs) {
    id
    copyrights {
      ...SlimCopyrightData
    }
  }
}

mutation SceneCopyrightsUpdate($sceneID: ID!, $copyrightIDs: [ID!]!) {
  sceneCopyrightsUpdate(scene_id: $sceneID, copyright_ids: $copyrightIDs) {
    id
    copyrights {
      ...SlimCopyrightData
    }
  }
}

mutation PerformerCopyrightsUpdate(
  $performerID: ID!
  $copyrightIDs: [ID!]!
) {
  performerCopyrightsUpdate(
    performer_id: $performerID
    copyright_ids: $copyrightIDs
  ) {
    id
    copyrights {
      ...SlimCopyrightData
    }
  }
}

mutation CopyrightImagesUpdate($copyrightID: ID!, $imageIDs: [ID!]!) {
  copyrightImagesUpdate(copyright_id: $copyrightID, image_ids: $imageIDs) {
    ...CopyrightData
  }
}

mutation CopyrightScenesUpdate($copyrightID: ID!, $sceneIDs: [ID!]!) {
  copyrightScenesUpdate(copyright_id: $copyrightID, scene_ids: $sceneIDs) {
    ...CopyrightData
  }
}

mutation CopyrightPerformersUpdate(
  $copyrightID: ID!
  $performerIDs: [ID!]!
) {
  copyrightPerformersUpdate(
    copyright_id: $copyrightID
    performer_ids: $performerIDs
  ) {
    ...CopyrightData
  }
}
