type Copyright {
  id: ID!
  name: String!
  sort_name: String!
  description: String!
  favorite: Boolean!
  aliases: [String!]!
  image_path: String!
  created_at: Time!
  updated_at: Time!
  parents: [Copyright!]!
  children: [Copyright!]!
  image_count: Int!
  scene_count: Int!
  performer_count: Int!
  images: [Image!]!
  scenes: [Scene!]!
  performers: [Performer!]!
}

input CopyrightCreateInput {
  name: String!
  sort_name: String
  description: String
  favorite: Boolean
  aliases: [String!]
  parent_ids: [ID!]
  child_ids: [ID!]
  image: String
}

input CopyrightUpdateInput {
  id: ID!
  name: String
  sort_name: String
  description: String
  favorite: Boolean
  aliases: [String!]
  parent_ids: [ID!]
  child_ids: [ID!]
  image: String
}

input CopyrightDestroyInput {
  id: ID!
}

type FindCopyrightsResultType {
  count: Int!
  copyrights: [Copyright!]!
}

extend type Query {
  findCopyright(id: ID!): Copyright
  findCopyrights(filter: FindFilterType, ids: [ID!]): FindCopyrightsResultType!
}

extend type Mutation {
  copyrightCreate(input: CopyrightCreateInput!): Copyright!
  copyrightUpdate(input: CopyrightUpdateInput!): Copyright!
  copyrightDestroy(input: CopyrightDestroyInput!): Boolean!
  imageCopyrightsUpdate(image_id: ID!, copyright_ids: [ID!]!): Image!
  sceneCopyrightsUpdate(scene_id: ID!, copyright_ids: [ID!]!): Scene!
  performerCopyrightsUpdate(performer_id: ID!, copyright_ids: [ID!]!): Performer!
  copyrightImagesUpdate(copyright_id: ID!, image_ids: [ID!]!): Copyright!
  copyrightScenesUpdate(copyright_id: ID!, scene_ids: [ID!]!): Copyright!
  copyrightPerformersUpdate(copyright_id: ID!, performer_ids: [ID!]!): Copyright!
}

extend type Image {
  copyrights: [Copyright!]!
}

extend type Scene {
  copyrights: [Copyright!]!
}

extend type Performer {
  copyrights: [Copyright!]!
}
